apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-17T11:04:22Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "4172"
  uid: 3d6d91aa-db5a-4430-a834-24dec6ee4d81
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.107.159.34
  clusterIPs:
  - 10.107.159.34
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31166
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
